# -*- coding: utf-8 -*-
"""ModelTraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12LPKi64S3cSAJ0hlSeU0xm_D95sUEdBZ
"""

# Imports

import pandas as pd
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

def getTrainSet(i):
  url = 'https://raw.githubusercontent.com/alexhg128/StocksClassifier/master/TrainSets/train_set_' + str(i).zfill(2) + '.csv'
  return pd.read_csv(url)

def createModel():
  return keras.Sequential([
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(2, activation='softmax')
  ])

def compileModel(model):
  model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy', 'categorical_accuracy',
                       'mean_squared_error', 'mean_absolute_error',
                       'mean_absolute_percentage_error'])

def trainModel(model, values, labels, epochs):
  model.fit(values, labels, epochs=epochs)

model = createModel()
compileModel(model)

for i in range(21):
  ts = getTrainSet(i + 1)
  ts.pop('Unnamed: 0')
  rec = ts.pop('rec')
  trainModel(model, ts.values, rec, 15)

model.history.history['accuracy'][-1]

model.save('stocks.h5')