# -*- coding: utf-8 -*-
"""TrainsetGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WjQCm2XYaYEZ5FQ48q1NI0e4w9qTmq7p
"""

# Imports

import pandas as pd
import sys

# Import dataset

url = 'https://raw.githubusercontent.com/alexhg128/StocksClassifier/master/Dataset/processed_prices.csv'
prices = pd.read_csv(url)

symbols = sorted(prices['symbol'].unique())

def printProgress(c, t):
  sys.stdout.write('\r[')
  x = int(c / t * 100)
  for y in range(x):
    sys.stdout.write('=')
  for y in range(100 - x):
    sys.stdout.write(' ')
  sys.stdout.write('] ' + str(c) + '/' + str(t))


def getTestSet(df):
  acceptable_gains = [ 0.05, 0.10, 0.15, 0.20 ]

  pr = pd.DataFrame([], columns=[
    'eps', 'pe', 'yield1', 'yield3', 'yield6', 'yield12', 'ma50', 'ma200',
    'ma300', 'rec', 'term', 'gain'
  ])

  total = df.shape[0]
  current = 0

  for k, p in df.iterrows():
    for g in acceptable_gains:
      # ST = 3
      choiceST = 0
      if (p['hi91'] / p['close']) - g > 1:
        choiceST = 1

      # MT = 6
      choiceMT = 0
      if (p['hi182'] / p['close']) - g > 1:
        choiceMT = 1

      # LT = 12
      choiceLT = 0
      if (p['hi365'] / p['close']) - g > 1:
        choiceLT = 1

      ST = pd.Series([
                      p['eps'], p['pe'], p['yield1'], p['yield3'], p['yield6'],
                      p['yield12'], p['ma50'] / p['close'], 
                      p['ma200'] / p['close'], p['ma300'] / p['close'],
                      choiceST, 3, g
                    ],
                    index=[
                      'eps', 'pe', 'yield1', 'yield3', 'yield6', 'yield12',
                      'ma50', 'ma200', 'ma300', 'rec', 'term', 'gain'
                    ])
      MT = pd.Series([
                      p['eps'], p['pe'], p['yield1'], p['yield3'], p['yield6'],
                      p['yield12'], p['ma50'] / p['close'], 
                      p['ma200'] / p['close'], p['ma300'] / p['close'],
                      choiceST, 3, g
                    ],
                    index=[
                      'eps', 'pe', 'yield1', 'yield3', 'yield6', 'yield12',
                      'ma50', 'ma200', 'ma300', 'rec', 'term', 'gain'
                    ])
      LT = pd.Series([
                      p['eps'], p['pe'], p['yield1'], p['yield3'], p['yield6'],
                      p['yield12'], p['ma50'] / p['close'], 
                      p['ma200'] / p['close'], p['ma300'] / p['close'],
                      choiceST, 3, g
                    ],
                    index=[
                      'eps', 'pe', 'yield1', 'yield3', 'yield6', 'yield12',
                      'ma50', 'ma200', 'ma300', 'rec', 'term', 'gain'
                    ])
      pr = pr.append(ST, ignore_index=True)
      pr = pr.append(MT, ignore_index=True)
      pr = pr.append(LT, ignore_index=True)
    current += 1
    printProgress(current, total)
  sys.stdout.write('\n')
  return pr

prev = 0

dfs = []

for i in range(21):
  s = symbols[prev:prev + 20]
  df = prices.loc[prices['symbol'].isin(s)]
  dfs.append(df)
  prev += 20

from google.colab import files

i = 1

for df in dfs:
  rf = getTestSet(df)
  rf.to_csv('train_set_' + str(i).zfill(2) + '.csv') 
  files.download('train_set_' + str(i).zfill(2) + '.csv')
  i += 1